### ISSUE TITLE
글씨 깨짐 현상

### ISSUE THREAD

**Issue by Weble21** [qowngus33/tetris#28]
실행 시 한국어 글씨 깨짐

**Comment by Weble21** [comment]
수정 부탁드립니다.

**Comment by qowngus33** [comment]
한글 깨짐 현상 수정해서 올려주세요

- [ ] SettingMenu
- [ ] SettingItem
- [ ] ScoreBoard

파일 확인부탁드립니다.

**Comment by Weble21** [comment]
해결했습니다.

**Comment by qowngus33** [comment]
확인했습니다.
