### ISSUE TITLE
인텔리제이 호환성에 관한 이슈

### ISSUE THREAD

**Issue by ks-RTUWD** [qowngus33/tetris#35]
인텔리제이로 파일을 열었을때 제대로 작동하지 않는 일이 발생하였음 - Run이 되지 않는
이를 해결하기 위해서 test코드와 src 코드를 분리하여 해결하였음
문제의 원인은 test파일이 src 파일 안에 있기에 main함수를 찾지 못하여 발생하였음
![image](https://user-images.githubusercontent.com/34408443/170427648-03a3a1f7-1ba6-487e-9c69-ebb379b425e0.png)

**Comment by qowngus33** [comment]
test src가 분리된 코드를 커밋해주시기 바랍니다.

**Comment by qowngus33** [comment]
Master branch에서 일어나는 conflict 또한 확인 부탁드립니다.
