### ISSUE TITLE
대전모드 변경에 있어서 tab키 누르면 포커스 나감

### ISSUE THREAD

**Issue by Weble21** [qowngus33/tetris#36]
게임 모드 바꾸는 키를 tab키로 지정하였는데, tab키를 누르면 focus가 나감.

**Comment by Weble21** [comment]
Tab키에서 Back_Space로 바꿔서 진행하겠습니다~

**Comment by qowngus33** [comment]
숫자 키로 변경하는거 고려해주세요

**Comment by Weble21** [comment]
싫어요

**Comment by Weble21** [comment]
숫자 키로 시도해봤는데, 버튼을 두 개로 만들면 fight mode로만 바뀌어서 그냥 하나로 진행하려 합니다.

**Comment by qowngus33** [comment]
넵 감사합니다.
