### ISSUE TITLE
Conflict 해결

### ISSUE THREAD

**Issue by qowngus33** [qowngus33/tetris#37]
복제된 파일이 있어 merge가 되지 않았습니다.
conflict를 해결해서 push 했으니
pull을 해서 확인 바랍니다.
conflict를 해결한 commit은 https://github.com/qowngus33/tetris/commit/f0b67d96f3656e4a83e9f05b37692daa9fd84692 입니다.

**Comment by Weble21** [comment]
이후 파일도 conflict나긴 했는데, 오류 해결한 후 커밋했습니다~
